### ISSUE TITLE
Issues 8/2

### ISSUE THREAD

**Issue by OhBall** [ramkbhattarai/GOCAMPING#3]
- [ ] Hover effects on demo user: add border to hover, and make margin the same for both hover and no hover.
- [ ] Change input sizes in modal.
- [ ] Finish Show Page (no reviews or bookings)
- [ ] Start search / index with google maps API

**Comment by ramkbhattarai** [comment]
<img width="1439" alt="Screen Shot 2019-08-28 at 7 08 21 AM" src="https://user-images.githubusercontent.com/46845773/66827593-07797080-ef1d-11e9-815d-c1acdd462065.png">

**Comment by ramkbhattarai** [comment]
<img width="1439" alt="Screen Shot 2019-08-28 at 7 08 21 AM" src="https://user-images.githubusercontent.com/46845773/66830818-60003c00-ef24-11e9-8ec0-a39a35d9a245.png">

**Comment by ramkbhattarai** [comment]
<img width="276" alt="Screen Shot 2019-10-15 at 8 25 51 AM" src="https://user-images.githubusercontent.com/46845773/66831361-75c23100-ef25-11e9-84b9-fcd85d5cc461.png">
